version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: youtube-manager-app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
